apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse.fullname" . }}-shared
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
data:
  shared.yaml: |
    {{- include "synapse.sharedConfigYaml" . | nindent 4 }}
