# Copyright (C) 2025 Famedly
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


# Build the Community Edition of Synapse, then build the Famedly Edition on top. Push
# both to their respective registries.

# TODO:
#  create a matrix with the last usable mod-packs
#  work out tag wrangling for all that
#  have 'on.pull_request' handling? This may have money attached if the runners/storage
#    aren't free. Perhaps just do the test building on amd64?
#  figure out why the push action is pushing when the value should be falsey(only push
#    when not a pull request)

name: Docker

on:
  push:
    tags: ["v*.*.*_*"]
    branches: ["jason/*"]
  workflow_dispatch:
    inputs:
      tags:
        description: "Tags to test with, should match expected 'vX.Y.Z_0' format(for now)"
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  community-build:
    # Since this will upload to ghcr.io, all we need is the github token. That is
    # automatically passed into the workflow.
    uses: famedly/github-workflows/.github/workflows/docker.yml@jason/docker-namespace
    with:
      push: ${{ github.event_name != 'pull_request' }} # Always build, don't publish on pull requests
      registry: ghcr.io
      image_name: famedly/synapse
      file: docker/Dockerfile
      # tag our new base image. If given a git tag of(as an example): "v1.234.5_6", this will
      # break down into a docker tag of "v1.234.5" and "latest". Since the trailing suffix is/was
      # used to differentiate new builds of Synapse typically with updated modules, it is
      # not needed here. "latest" comes from the 'auto' functionality of flavors used
      # when the tag is based on(in this case) a pattern and requires no explicit enablement.
      tags: |
        type=match,group=1,pattern=(v\d+.\d+.\d+)_\d+

#  calculate_mod_build:
#    if: ${{ !cancelled() && !failure() }} # Allow for stopping the build job
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: "3.x"
#      - id: get-matrix
#        run: .ci/scripts/calculate_builds.py
#    outputs:
#      build_matrix: ${{ steps.get-matrix.outputs.build_matrix }}

  production-build:
    if: ${{ !cancelled() && !failure() }} # Allow for stopping the build job
    needs:
      - community-build
#      - calculate_mod_build
#    strategy:
#      matrix:
#        job:  ${{ fromJson(needs.calculate_mod_build.outputs.build_matrix) }}
    uses: famedly/github-workflows/.github/workflows/docker.yml@jason/docker-namespace
    with:
      push: false
#      push: ${{ github.event_name != 'pull_request' }} # Always build, don't publish on pull requests
      registry_user: famedly-ci
      registry: docker-oss.nexus.famedly.de
      image_name: synapse
      file: docker/Dockerfile-famedly
      build_args: "[FROM=ghcr.io/famedly/synapse:latest]"
      # tag the production image used for famedly deployments.
      # This will create 3 tags on a given image. If(for example like above) we provide
      # a git tag of "v1.234.5_6", it will be broken into 3 docker tags:
      # "latest"
      # "v1.234.5"
      # "v1.234.5_6"
      tags: |
        type=match,group=1,pattern=(v\d+.\d+.\d+)_\d+
        type=match,group=1,pattern=(v\d+.\d+.\d+_\d+)
    secrets: inherit
