# GitHub actions workflow to build and push base docker images for pull requests.
name: Build Dev Docker Image on PR

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-build-and-push-ghcr:
    uses: famedly/github-workflows/.github/workflows/docker.yml@jason-docker-namespace
    with:
      push: true
      registry: ghcr.io
      image_name: famedly/synapse
      file: docker/Dockerfile
      tags: |
        type=ref,event=pr
      flavor: |
        latest=false
        prefix=dev-

  dev-build-and-push-nexus:
    uses: famedly/github-workflows/.github/workflows/docker.yml@jason-docker-namespace
    with:
      push: true
      registry: docker-oss.nexus.famedly.de
      registry_user: famedly-ci
      image_name: synapse
      file: docker/Dockerfile
      tags: |
        type=ref,event=pr
      flavor: |
        latest=false
        prefix=dev-
    secrets: inherit
